version: "3"

services:
  api:
    build: ./
    command: npm run start api -- --host=0.0.0.0
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      PORT: 3333
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgrespasswd
      POSTGRES_HOST: postgres
      POSTGRES_DB: shane_chat
      POSTGRES_PORT: 5432
    ports:
      - "3333:3333"
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules

  postgres:
    image: postgres:14-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgrespasswd
      POSTGRES_DB: shane_chat
      PGDATA: /var/lib/postgres/data/pgdata
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 5s
      retries: 5
    ports:
      - "15432:5432"
    volumes:
      - ~/.shane-chat/postgres:/var/lib/postgres/data/pgdata

  ui:
    build: ./
    command: npm start chat -- --host=0.0.0.0
    environment:
      PORT: 4200
      API_URL: 127.0.0.1:3333
    ports:
      - "4200:4200"
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
